# Meta Data for SEO

## Homepage
title = "ntemposd"
titleSeparator = "-"
titleAddition = "Personal Website"
description = "Hi! I'm Dimitri, widely known as ntemposd. My passion is to facilitate the creation of cut edge tech products."

## Open Graph + Twitter Cards
images = ["ntemposd.png"]
twitterSite = "ntemposd"
twitterCreator = "ntemposd"
facebookAuthor = "ntemposd"
facebookPublisher = "ntemposd"
ogLocale = "en_US"

## JSON-LD
schemaType = "CreativeWork"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/ntemposd"
schemaLinkedIn = "https://www.linkedin.com/in/ntemposd/"
schemaGitHub = "https://github.com/ntemposd"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = false
  breadCrumb = false
  highLight = true
  kaTex = false
